bet/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from views import PrognostikaListView
from django.contrib.sitemaps.views import sitemap
from bet.sitemaps import ArticleSitemap
from .api import v1_api
from feeds import LatestEntriesFeed

sitemaps = {
   'posts': ArticleSitemap,
}

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'r'(?P<post>[-\w]+)/$', views.post_detail,name='post_detail'),
    url(r'^ajax_newsletter/$', views.ajax_newsletter, name='ajax_newsletter'),
    url(r'^kouponi', views.kouponi, name='kouponi'),
    url(r'^livescore', views.livescore, name='livescore'),
    url(r'^apodoseis', views.apodoseis, name='apodoseis'),
    url(r'^livestreaming', views.livestreaming, name='livestreaming'),
    url(r'^asianhandicap', views.asianhandicap, name='asianhandicap'),
    url(r'^tziroi', views.tziroi, name='tziroi'),
    url(r'^statistika', views.statistika, name='statistika'),
    url(r'^bonus', views.bonus, name='bonus'),
    url(r'^contact$', views.contact,name='contact'),
    url(r'^tables', views.tables, name='tables'),
    url(r'^newsletter/', views.newsletter,name='newsletter'),
    url(r'^category/analiseis/$', views.analiseis,name='analiseis'),
    url(r'^login/$',auth_views.login,name='login'),
    url(r'^logout/$',auth_views.logout,name='logout'),
    url(r'^logout-then-login/$',auth_views.logout_then_login,name='logout_then_login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^prognostika-list/$', PrognostikaListView.as_view(), name='prognostika-list'),


    # login / logout urls

    #url(r'^$', views.dashboard, name='dashboard'),
    url(r'^password-change/$',auth_views.password_change,{'post_change_redirect' : '/registration/password-change/done',},name='password_change'),
    url(r'^password-change/done/$',auth_views.password_change_done,name='password_change_done'),
    # restore password urls
    url(r'^password-reset/$',auth_views.password_reset,{'template_name':'registration/passsword_reset_form.html','post_reset_redirect' : '/registration/password-rest/done'},name='password_reset'),
    url(r'^password-reset/done/$',auth_views.password_reset_done,name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.password_reset_confirm,{'post_reset_redirect' : '/registration/password-reset/complete'},name='password_reset_confirm'),
    url(r'^password-reset/complete/$',auth_views.password_reset_complete,name='password_reset_complete'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'list/$',views.post_list, name = 'post_list'),
    url(r'^api/', include(v1_api.urls)),
    #url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'r'(?P<post>[-\w]+)/$',views.post_detail,name='post_detail'),
    url(r'^category/(?P<tag_slug>[-\w]+)/$', views.post_list,name='post_list_by_tag'),
	url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    url(r'^rss/$', LatestEntriesFeed()),
    #url(r'^(?P<post>[\w-]+)/$', views.post_detail,name='post_detail'),
    #url( r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]

betvision/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bet.urls', namespace='bet', app_name='bet')),
]

bet/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


# class Tag(models.Model):
#     title = models.CharField(max_length=100)
#     def __str__(self):
#         return self.title
#
#     def __unicode__(self):
#         return u'%s' % (self.title)

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Article(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=500)
    body = RichTextField()
    slug = models.SlugField(max_length=500,unique_for_date='publish')
    image = models.ImageField(upload_to='images',null=True)
    tags = TaggableManager()
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')
    published = PublishedManager()

    # def get_absolute_url(self):
    #     return reverse('bet:post_detail',
    #                    args=[self.slug])
    def get_absolute_url(self):
        return reverse('bet:post_detail',
                       args=[self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

    def get_image_absolute_url(self):
        return 'http://127.0.0.1:8000'+self.image.url

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return u'%s' % (self.title)

class Prognostika(models.Model):
    kodikos = models.CharField(max_length=500)
    agonas = models.CharField(max_length=500)
    apodosi = models.CharField(max_length=500)
    simeio = models.CharField(max_length=500)
    apotelesma = models.CharField(max_length=500)
    bookmaker_link = models.CharField(max_length=500)
    bookmaker_title = models.CharField(max_length=500,null=True)
    date = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    SPORTS = (
        ('football', 'Ποδόσφαιρο'),
        ('basketball', 'Μπάσκετ'),
        ('tennis', 'Τέννις'),
        ('volley', 'Βόλλευ'),
    )
    sport = models.CharField(max_length=10, choices=SPORTS, default='football')
    SIMEIA = (
        ('nulls', 'Κανένα'),
        ('success', 'Κερδισμένο'),
        ('danger', 'Χαμένο'),
    )
    xroma = models.CharField(max_length=10, choices=SIMEIA, default='nulls')


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.kodikos

    def __unicode__(self):
        return u'%s' % (self.kodikos)



class Block(models.Model):
    objects=models.Manager()
    CHOICES = [(i, i) for i in range(11)]
    SIDEBAR = (
        ('left', 'Left'),
        ('right', 'Right'),
        ('arxiki1', 'Αρχικη 1'),
        ('arxiki2', 'Αρχικη 2'),
        ('arxiki3', 'Αρχικη 3'),
        ('arxikipano', 'Αρχικη πανω'),
    )
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=500)
    body = RichTextField()
    weight = models.IntegerField(choices=CHOICES)
    titleOn = models.BooleanField(default=True)
    sidebar = models.CharField(max_length=10, choices=SIDEBAR, default='right')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')
    published = PublishedManager()

    def __str__(self):
        return self.title

    def __unicode__(self):
        return u'%s' % (self.title)

    class Meta:
        ordering = ('-weight',)


class Newsletter(models.Model):
    newsemail = models.EmailField(unique=True)

bet/forms.py
# coding=utf-8
from django import forms
from taggit_labels.widgets import LabelWidget
from taggit.forms import TagField
from .models import Newsletter
from django.contrib.auth.models import User

class ArticleAdminForm(forms.ModelForm):
   tags = TagField(required=False, widget=LabelWidget)

   # def __init__(self, *args, **kwargs):
   #     super(ArticleAdminForm, self).__init__(*args, **kwargs)
   #     self.fields['image'].required = False

class NewsletterForm(forms.ModelForm):

    class Meta:
      model = Newsletter
      fields = '__all__'

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs \
            .update({
            'placeholder': 'Κωδικός Χρήστη',
        })
        self.fields['password'].widget.attrs \
            .update({
            'placeholder': '******',
        })

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                              widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                               widget=forms.PasswordInput)
    email = forms.CharField(max_length=75, required=True)
    val = forms.CharField(label='Πόσο κάνει πέντε συν τέσσερα; ')


    class Meta:
       model = User
       fields = ('username', 'first_name', 'email',)


    def clean_password2(self):
       cd = self.cleaned_data
       if cd['password'] != cd['password2']:
           raise forms.ValidationError('Passwords don\'t match.')
       return cd['password2']
    def clean_val(self):
        cd=self.cleaned_data
        if cd['val'] != '9':
            raise forms.ValidationError('Λάθος αριθμός.')
        return cd['val']


class UserEditForm(forms.ModelForm):
    class Meta:
       model = User
       fields = ('first_name', 'last_name', 'email')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)
    

bet/views.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from .models import Article,Block,Prognostika,Newsletter
from django.db.models import Count
from .forms import NewsletterForm,LoginForm, UserRegistrationForm,UserEditForm,ContactForm
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .common.decorators import ajax_required

def index(request):
    block1 = Block.published.filter(sidebar='arxiki1')[:1]
    block2 = Block.published.filter(sidebar='arxiki2')[:1]
    block3 = Block.published.filter(sidebar='arxiki3')[:1]
    return render(request, "index.html",{'block1': block1, 'block2':block2,'block3':block3})

def kouponi(request):
    return render(request, "bet/kouponi.html")

def bonus(request):
    return render(request, "bet/bonus.html")

def tables(request):
    return render(request, "bet/tables.html")

def apodoseis(request):
    return render(request, "bet/apodoseis.html")

def statistika(request):
    return render(request, "bet/statistika.html")

def asianhandicap(request):
    return render(request, "bet/asianhandicap.html")

def tziroi(request):
    return render(request, "bet/tziroi.html")

def livestreaming(request):
    return render(request, "bet/livestreaming.html")

def livescore(request):
    return render(request, "bet/kouponi.html")

class PrognostikaListView(ListView):
    model = Prognostika

def contact(request):
    sent = False
    if request.method == 'POST':
       # Form was submitted
       form = ContactForm(request.POST)
       if form.is_valid():
           # Form fields passed validation
           cd = form.cleaned_data
           subject = '{}  Message from  "{}"'.format(cd['name'], cd['email'])
           message = 'Read  at {}\n\n{}\'s comments: '.format(cd['name'], cd['comments'])
           send_mail(subject, message, cd['email'],['betvisionsports@gmail.com'])
           sent = True
           # ... send email
    else:
       form = ContactForm()
    return render(request, 'bet/contact.html', {'form': form, 'sent':sent})

def post_list(request, tag_slug = None):
    object_list = Article.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 15)  # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'bet/article_list.html', {'page': page, 'posts': posts, 'tag': tag})

def analiseis(request):
    object_list = Article.published.filter(tags__name__in=["Αναλύσεις Βόλλευ","Αναλύσεις Τένις"])
    paginator = Paginator(object_list, 15)  # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'bet/article_analiseis.html', {'page': page, 'posts': posts})

def post_detail(request,post,year,month,day,):
    post = get_object_or_404(Article,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Article.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:3]
    show_image = post.tags.slugs()
    return render(request, 'bet/article.html', {'post': post, 'similar_posts': similar_posts,'show_image':show_image})


def newsletter(request):
    if request.method == 'POST':
        newsletter = NewsletterForm(data=request.POST)
        if newsletter.is_valid():
            newsletter.save()
            messages.success(request, 'Το email σας προστέθηκε επιτυχώς')
            cssClass = 'success'
            return render(request,'index.html', {'cssClass': cssClass})

    else:
        newsletter = NewsletterForm()
        return redirect('/',request.META.get('HTTP_REFERER'))
    messages.error(request, 'Το email σας υπάρχει ηδη καταχωρημένο')
    cssClass = 'danger'
    return render(request, 'index.html', {'cssClass': cssClass})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'Authenticated successfully')
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

@login_required
def dashboard(request):
   return render(request, 'registration/dashboard.html', {'section': 'dashboard'})

def register(request):
    if request.method == 'POST':
       user_form = UserRegistrationForm(request.POST)
       if user_form.is_valid():
           # Create a new user object but avoid saving it yet
           new_user = user_form.save(commit=False)
           # Set the chosen password
           new_user.set_password(user_form.cleaned_data['password'])
           # Save the User object
           new_user.save()
           return render(request,'registration/register_done.html',{'new_user': new_user})
    else:
       user_form = UserRegistrationForm()
    return render(request,'registration/register.html',{'user_form': user_form})

@login_required
def edit(request):
   if request.method == 'POST':
       user_form = UserEditForm(instance=request.user,
                                data=request.POST)

       if user_form.is_valid():
           user_form.save()
           messages.success(request, 'Profile updated '\
                                         'successfully')
       else:
           messages.error(request, 'Error updating your profile')
   else:
       user_form = UserEditForm(instance=request.user)

   return render(request,
                 'registration/edit.html',
                 {'user_form': user_form,})

@ajax_required
@require_POST
def ajax_newsletter(request):
    post_val = request.POST.get('newsmail')

    if post_val :
        newsletter = Newsletter(newsemail=post_val)
        saving = newsletter.save()
        if saving:
            return JsonResponse({'status':'ok'})
        else:
            return JsonResponse({'status':'false'})
    else:
        return JsonResponse({'status': 'false'})

bet/templates/partials/breaking-bar.html
{% load bet_tags %}

<div id="breaking-bar" class="c5-single-element c5-breaking-1170-S-C-B">
                        <div class="c5-breaking-wrap no-controller">
                <p class="breaking-title">Τελευταία Άρθρα</p>
                            <ul id="c5-webTicker">
                               {% breaking_bar %}
                            </ul>
                        </div>
        </div>

bet/templates/partials/mobile.html
{% load staticfiles %}
<div class="c5-mobile-hidden-wrap">
    <span class="fa fa-close c5-close-mobile-sidebar"></span>
    <div class="c5-mobile-logo">
        <a class="clearfix c5-orignial-logo c5-logo c5-bottom-30" style="margin-top:15px" href="{% url "bet:index" %}" rel="nofollow"><img alt="Logo" src="{% static 'images/logo.png' %}" srcset="{% static 'images/logo.png' %} 1x, {% static 'images/logo.png' %} 2x" />
        </a>
    </div>
    <div class="c5-mobile-main-menu">
        <nav role="navigation" class="navigation-shortcode responsive-off light default top-menu-nav clearfix">
            <div class="responsive-controller clearfix"><span class="menu-enable fa fa-align-justify"></span>
            </div>

            <ul id="menu-sidebar" class=" top-nav menu-sc-nav clearfix">

                        <li id="menu-item-6299" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:prognostika-list" %}" class=" "><span class=" "></span><span>ΠΡΟΓΝΩΣΤΙΚΑ</span></a>
                        </li>
                        

                <li id="menu-item-6212" class="menu-item menu-item-type-taxonomy menu-item-object-category category-7"><a href="{% url "bet:kouponi"  %}" class=" "><span class=" "></span><span>ΚΟΥΠΟΝΙ</span></a>
                </li>

                        <li id="menu-item-6299" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:post_list_by_tag" "analyseis-podosfairoy" %}" class=" "><span class=" "></span><span>ΑΝΑΛΥΣΕΙΣ ΠΟΔΟΣΦΑΙΡΟΥ</span></a>
                        </li>
                        <li id="menu-item-6268" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:post_list_by_tag" "analyseis-mpasket" %}" class=" "><span class=" "></span><span>ΑΝΑΛΥΣΕΙΣ ΜΠΑΣΚΕΤ</span></a>
                        </li>
                        <li id="menu-item-6265" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:post_list_by_tag" "analyseis-tenis" %}" class=" "><span class=" "></span><span>ΑΝΑΛΥΣΕΙΣ ΤΕΝΝΙΣ</span></a>
                        </li>
                        <li id="menu-item-6264" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:post_list_by_tag" "analyseis-bolley" %}" class=" "><span class=" "></span><span>ΑΝΑΛΥΣΕΙΣ ΒΟΛΛΕΥ</span></a>

                </li>
                <li id="menu-item-6228" class="menu-item menu-item-type-taxonomy menu-item-object-category category-4"><a href="{% url "bet:tables" %}" class=" "><span class=" "></span><span>ΒΑΘΜΟΛΟΓΙΕΣ</span></a>
                </li>
                <li id="menu-item-6209" class="menu-item menu-item-type-taxonomy menu-item-object-category category-3"><a href="{% url "bet:livescore" %}" class=" "><span class=" "></span><span>LIVESCORE</span></a>
                </li>
                <li id="menu-item-6208" class="menu-item menu-item-type-taxonomy menu-item-object-category category-2"><a href="{% url "bet:post_list_by_tag" "news" %}" class=" "><span class=" "></span><span>ΕΙΔΗΣΕΙΣ</span></a>
                </li>
                <li id="menu-item-6224" class="menu-item menu-item-type-taxonomy menu-item-object-category category-8"><a href="{% url "bet:post_list_by_tag" "stoixhmatikh-8ewria" %}" class=" "><span class=" "></span><span>ΣΤΟΙΧΗΜΑΤΙΚΗ ΘΕΩΡΙΑ</span></a>
                </li>
                <li id="menu-item-6210" class="menu-item menu-item-type-taxonomy menu-item-object-category category-5"><a href="{% url "bet:post_list_by_tag" "nomo8esia" %}" class=" "><span class=" "></span><span>ΝΟΜΟΘΕΣΙΑ</span></a>
                </li>


                        <li id="menu-item-6299" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:apodoseis" %}" class=" "><span class=" "></span><span>ΠΤΩΣΗ ΑΠΟΔΟΣΕΩΝ</span></a>
                        </li>
                        <li id="menu-item-6268" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url  "bet:tziroi" %}" class=" "><span class=" "></span><span>ΤΖΙΡΟΙ</span></a>
                        </li>
                        <li id="menu-item-6265" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:livestreaming"  %}" class=" "><span class=" "></span><span>LIVE STREAMING</span></a>
                        </li>
                        <li id="menu-item-6264" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:statistika"  %}" class=" "><span class=" "></span><span>ΣΤΑΤΙΣΤΙΚΑ</span></a>
                        </li>
                        <li id="menu-item-6264" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:asianhandicap"  %}" class=" "><span class=" "></span><span>ASIAN HANDICAP</span></a>
                        </li>


            </ul>
        </nav>
    </div>

    {% include "partials/sidebar-right-mobile.html" %} {% include "partials/sidebar-left-mobile.html" %}
</div>

bet/templates/partials/sidebar-left.html
 {% load bet_tags %}

  <div id="small-sidebar" class="c5-single-element c5-sidebar-small-1170-S-C-B">
                            <div class="c5-sidebar-parent-wrap">
                                <div class="c5-sidebar-wrap">
                                    <nav role="navigation" class="navigation-shortcode responsive-no_responsive light sidebar top-menu-nav clearfix"><div class="responsive-controller clearfix"><span class="menu-enable fa fa-align-justify"></span></div><ul id="menu-sidebar-1" class=" top-nav menu-sc-nav clearfix">
<li  id="menu-item-6212" class="menu-item menu-item-type-taxonomy menu-item-object-category category-7"><a href="{% url "bet:prognostika-list"  %}"  class=" " ><span class=" "></span><span>ΠΡΟΓΝΩΣΤΙΚΑ</span></a></li>

<li  id="menu-item-6212" class="menu-item menu-item-type-taxonomy menu-item-object-category category-7"><a href="{% url "bet:kouponi"  %}"  class=" " ><span class=" "></span><span>ΚΟΥΠΟΝΙ</span></a></li>
<li  id="menu-item-6228" class="menu-item menu-item-type-taxonomy menu-item-object-category category-4"><a href="#"  class=" " ><span class=" "></span><span>ΑΝΑΛΥΣΕΙΣ</span></a>
<ul class="sub-menu">
	<li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:post_list_by_tag" "analyseis-podosfairoy" %}"  class=" " ><span class=" "></span><span>Ποδόσφαιρο</span></a></li>
	<li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:post_list_by_tag" "analyseis-mpasket" %}"  class=" " ><span class=" "></span><span>Μπάσκετ</span></a></li>
	<li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:post_list_by_tag" "analyseis-tenis" %}"  class=" " ><span class=" "></span><span>Τένις</span></a></li>
	<li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:post_list_by_tag" "analyseis-bolley" %}"  class=" " ><span class=" "></span><span>Βόλλευ</span></a></li>
</ul>
</li>
<li  id="menu-item-6209" class="menu-item menu-item-type-taxonomy menu-item-object-category category-3"><a href="{% url "bet:tables" %}"  class=" " ><span class=" "></span><span>ΒΑΘΜΟΛΟΓΙΕΣ</span></a></li>
<li  id="menu-item-6208" class="menu-item menu-item-type-taxonomy menu-item-object-category category-2"><a href="{% url "bet:livescore" %}"  class=" " ><span class=" "></span><span>LIVESCORE</span></a></li>
<li  id="menu-item-6224" class="menu-item menu-item-type-taxonomy menu-item-object-category category-8"><a href="{% url "bet:post_list_by_tag" "news" %}"  class=" " ><span class=" "></span><span>ΕΙΔΗΣΕΙΣ</span></a></li>
<li  id="menu-item-6210" class="menu-item menu-item-type-taxonomy menu-item-object-category category-5"><a href="{% url "bet:post_list_by_tag" "stoixhmatikh-8ewria" %}"  class=" " ><span class=" "></span><span>ΣΤΟΙΧΗΜΑΤΙΚΗ ΘΕΩΡΙΑ</span></a></li>
<li  id="menu-item-6210" class="menu-item menu-item-type-taxonomy menu-item-object-category category-5"><a href="{% url "bet:post_list_by_tag" "nomo8esia" %}"  class=" " ><span class=""></span><span>ΝΟΜΟΘΕΣΙΑ</span></a></li>
<li  id="menu-item-6211" class="menu-item menu-item-type-taxonomy menu-item-object-category current-post-ancestor current-menu-parent current-post-parent category-6"><a href="#"  class=" " ><span class=""></span><span>ΕΡΓΑΛΕΙΑ</span></a>
<ul class="sub-menu">
	<li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:apodoseis" %}"  class=" " ><span class=" "></span><span>Πτώση Αποδόσεων</span></a></li>
	<li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:tziroi"  %}"  class=" " ><span class=" "></span><span>Τζίροι</span></a></li>
	<li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:livestreaming"  %}"  class=" " ><span class=" "></span><span>Live Streaming</span></a></li>
    <li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:statistika"  %}"  class=" " ><span class=" "></span><span>Στατιστικά</span></a></li>
      <li  id="menu-item" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="{% url "bet:asianhandicap"  %}"  class=" " ><span class=" "></span><span>Asian Handicap</span></a></li>
</ul>
</li>
</ul></nav>
                                    <div id="sidebar-small_sidebar" class="c5-sidebar-wrap clearfix">



                            {% sidebar_left %}




                    </div>
                                        </div>
                            </div>

                        </div>