bet/urls.py
from django.conf.urls import url,include
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from views import PrognostikaListView
from django.contrib.sitemaps.views import sitemap
from bet.sitemaps import ArticleSitemap
from .api import v1_api
from feeds import LatestEntriesFeed

sitemaps = {
   'posts': ArticleSitemap,
}

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'r'(?P<post>[-\w]+)/$', views.post_detail,name='post_detail'),
    url(r'^ajax_newsletter/$', views.ajax_newsletter, name='ajax_newsletter'),
    url(r'^kouponi', views.kouponi, name='kouponi'),
    url(r'^livescore', views.livescore, name='livescore'),
    url(r'^apodoseis', views.apodoseis, name='apodoseis'),
    url(r'^livestreaming', views.livestreaming, name='livestreaming'),
    url(r'^asianhandicap', views.asianhandicap, name='asianhandicap'),
    url(r'^tziroi', views.tziroi, name='tziroi'),
    url(r'^statistika', views.statistika, name='statistika'),
    url(r'^bonus', views.bonus, name='bonus'),
    url(r'^contact$', views.contact,name='contact'),
    url(r'^tables', views.tables, name='tables'),
    url(r'^newsletter/', views.newsletter,name='newsletter'),
    url(r'^category/analiseis/$', views.analiseis,name='analiseis'),
    url(r'^login/$',auth_views.login,name='login'),
    url(r'^logout/$',auth_views.logout,name='logout'),
    url(r'^logout-then-login/$',auth_views.logout_then_login,name='logout_then_login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^prognostika-list/$', PrognostikaListView.as_view(), name='prognostika-list'),


    # login / logout urls

    #url(r'^$', views.dashboard, name='dashboard'),
    url(r'^password-change/$',auth_views.password_change,{'post_change_redirect' : '/registration/password-change/done',},name='password_change'),
    url(r'^password-change/done/$',auth_views.password_change_done,name='password_change_done'),
    # restore password urls
    url(r'^password-reset/$',auth_views.password_reset,{'template_name':'registration/passsword_reset_form.html','post_reset_redirect' : '/registration/password-rest/done'},name='password_reset'),
    url(r'^password-reset/done/$',auth_views.password_reset_done,name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',auth_views.password_reset_confirm,{'post_reset_redirect' : '/registration/password-reset/complete'},name='password_reset_confirm'),
    url(r'^password-reset/complete/$',auth_views.password_reset_complete,name='password_reset_complete'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'list/$',views.post_list, name = 'post_list'),
    url(r'^api/', include(v1_api.urls)),
    #url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'r'(?P<post>[-\w]+)/$',views.post_detail,name='post_detail'),
    url(r'^category/(?P<tag_slug>[-\w]+)/$', views.post_list,name='post_list_by_tag'),
	url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    url(r'^rss/$', LatestEntriesFeed()),
    #url(r'^(?P<post>[\w-]+)/$', views.post_detail,name='post_detail'),
    #url( r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]

betvision/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bet.urls', namespace='bet', app_name='bet')),
]

bet/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


# class Tag(models.Model):
#     title = models.CharField(max_length=100)
#     def __str__(self):
#         return self.title
#
#     def __unicode__(self):
#         return u'%s' % (self.title)

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Article(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=500)
    body = RichTextField()
    slug = models.SlugField(max_length=500,unique_for_date='publish')
    image = models.ImageField(upload_to='images',null=True)
    tags = TaggableManager()
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')
    published = PublishedManager()

    # def get_absolute_url(self):
    #     return reverse('bet:post_detail',
    #                    args=[self.slug])
    def get_absolute_url(self):
        return reverse('bet:post_detail',
                       args=[self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

    def get_image_absolute_url(self):
        return 'http://127.0.0.1:8000'+self.image.url

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return u'%s' % (self.title)

class Prognostika(models.Model):
    kodikos = models.CharField(max_length=500)
    agonas = models.CharField(max_length=500)
    apodosi = models.CharField(max_length=500)
    simeio = models.CharField(max_length=500)
    apotelesma = models.CharField(max_length=500)
    bookmaker_link = models.CharField(max_length=500)
    bookmaker_title = models.CharField(max_length=500,null=True)
    date = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    SPORTS = (
        ('football', 'Ποδόσφαιρο'),
        ('basketball', 'Μπάσκετ'),
        ('tennis', 'Τέννις'),
        ('volley', 'Βόλλευ'),
    )
    sport = models.CharField(max_length=10, choices=SPORTS, default='football')
    SIMEIA = (
        ('nulls', 'Κανένα'),
        ('success', 'Κερδισμένο'),
        ('danger', 'Χαμένο'),
    )
    xroma = models.CharField(max_length=10, choices=SIMEIA, default='nulls')


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.kodikos

    def __unicode__(self):
        return u'%s' % (self.kodikos)



class Block(models.Model):
    objects=models.Manager()
    CHOICES = [(i, i) for i in range(11)]
    SIDEBAR = (
        ('left', 'Left'),
        ('right', 'Right'),
        ('arxiki1', 'Αρχικη 1'),
        ('arxiki2', 'Αρχικη 2'),
        ('arxiki3', 'Αρχικη 3'),
        ('arxikipano', 'Αρχικη πανω'),
    )
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=500)
    body = RichTextField()
    weight = models.IntegerField(choices=CHOICES)
    titleOn = models.BooleanField(default=True)
    sidebar = models.CharField(max_length=10, choices=SIDEBAR, default='right')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')
    published = PublishedManager()

    def __str__(self):
        return self.title

    def __unicode__(self):
        return u'%s' % (self.title)

    class Meta:
        ordering = ('-weight',)


class Newsletter(models.Model):
    newsemail = models.EmailField(unique=True)

bet/forms.py
# coding=utf-8
from django import forms
from taggit_labels.widgets import LabelWidget
from taggit.forms import TagField
from .models import Newsletter
from django.contrib.auth.models import User

class ArticleAdminForm(forms.ModelForm):
   tags = TagField(required=False, widget=LabelWidget)

   # def __init__(self, *args, **kwargs):
   #     super(ArticleAdminForm, self).__init__(*args, **kwargs)
   #     self.fields['image'].required = False

class NewsletterForm(forms.ModelForm):

    class Meta:
      model = Newsletter
      fields = '__all__'

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs \
            .update({
            'placeholder': 'Κωδικός Χρήστη',
        })
        self.fields['password'].widget.attrs \
            .update({
            'placeholder': '******',
        })

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                              widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                               widget=forms.PasswordInput)
    email = forms.CharField(max_length=75, required=True)
    val = forms.CharField(label='Πόσο κάνει πέντε συν τέσσερα; ')


    class Meta:
       model = User
       fields = ('username', 'first_name', 'email',)


    def clean_password2(self):
       cd = self.cleaned_data
       if cd['password'] != cd['password2']:
           raise forms.ValidationError('Passwords don\'t match.')
       return cd['password2']
    def clean_val(self):
        cd=self.cleaned_data
        if cd['val'] != '9':
            raise forms.ValidationError('Λάθος αριθμός.')
        return cd['val']


class UserEditForm(forms.ModelForm):
    class Meta:
       model = User
       fields = ('first_name', 'last_name', 'email')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)
    

bet/views.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from .models import Article,Block,Prognostika,Newsletter
from django.db.models import Count
from .forms import NewsletterForm,LoginForm, UserRegistrationForm,UserEditForm,ContactForm
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .common.decorators import ajax_required

def index(request):
    block1 = Block.published.filter(sidebar='arxiki1')[:1]
    block2 = Block.published.filter(sidebar='arxiki2')[:1]
    block3 = Block.published.filter(sidebar='arxiki3')[:1]
    return render(request, "index.html",{'block1': block1, 'block2':block2,'block3':block3})

def kouponi(request):
    return render(request, "bet/kouponi.html")

def bonus(request):
    return render(request, "bet/bonus.html")

def tables(request):
    return render(request, "bet/tables.html")

def apodoseis(request):
    return render(request, "bet/apodoseis.html")

def statistika(request):
    return render(request, "bet/statistika.html")

def asianhandicap(request):
    return render(request, "bet/asianhandicap.html")

def tziroi(request):
    return render(request, "bet/tziroi.html")

def livestreaming(request):
    return render(request, "bet/livestreaming.html")

def livescore(request):
    return render(request, "bet/kouponi.html")

class PrognostikaListView(ListView):
    model = Prognostika

def contact(request):
    sent = False
    if request.method == 'POST':
       # Form was submitted
       form = ContactForm(request.POST)
       if form.is_valid():
           # Form fields passed validation
           cd = form.cleaned_data
           subject = '{}  Message from  "{}"'.format(cd['name'], cd['email'])
           message = 'Read  at {}\n\n{}\'s comments: '.format(cd['name'], cd['comments'])
           send_mail(subject, message, cd['email'],['betvisionsports@gmail.com'])
           sent = True
           # ... send email
    else:
       form = ContactForm()
    return render(request, 'bet/contact.html', {'form': form, 'sent':sent})

def post_list(request, tag_slug = None):
    object_list = Article.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 15)  # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'bet/article_list.html', {'page': page, 'posts': posts, 'tag': tag})

def analiseis(request):
    object_list = Article.published.filter(tags__name__in=["Αναλύσεις Βόλλευ","Αναλύσεις Τένις"])
    paginator = Paginator(object_list, 15)  # 2 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'bet/article_analiseis.html', {'page': page, 'posts': posts})

def post_detail(request,post,year,month,day,):
    post = get_object_or_404(Article,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Article.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:3]
    show_image = post.tags.slugs()
    return render(request, 'bet/article.html', {'post': post, 'similar_posts': similar_posts,'show_image':show_image})


def newsletter(request):
    if request.method == 'POST':
        newsletter = NewsletterForm(data=request.POST)
        if newsletter.is_valid():
            newsletter.save()
            messages.success(request, 'Το email σας προστέθηκε επιτυχώς')
            cssClass = 'success'
            return render(request,'index.html', {'cssClass': cssClass})

    else:
        newsletter = NewsletterForm()
        return redirect('/',request.META.get('HTTP_REFERER'))
    messages.error(request, 'Το email σας υπάρχει ηδη καταχωρημένο')
    cssClass = 'danger'
    return render(request, 'index.html', {'cssClass': cssClass})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.success(request, 'Authenticated successfully')
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})

@login_required
def dashboard(request):
   return render(request, 'registration/dashboard.html', {'section': 'dashboard'})

def register(request):
    if request.method == 'POST':
       user_form = UserRegistrationForm(request.POST)
       if user_form.is_valid():
           # Create a new user object but avoid saving it yet
           new_user = user_form.save(commit=False)
           # Set the chosen password
           new_user.set_password(user_form.cleaned_data['password'])
           # Save the User object
           new_user.save()
           return render(request,'registration/register_done.html',{'new_user': new_user})
    else:
       user_form = UserRegistrationForm()
    return render(request,'registration/register.html',{'user_form': user_form})

@login_required
def edit(request):
   if request.method == 'POST':
       user_form = UserEditForm(instance=request.user,
                                data=request.POST)

       if user_form.is_valid():
           user_form.save()
           messages.success(request, 'Profile updated '\
                                         'successfully')
       else:
           messages.error(request, 'Error updating your profile')
   else:
       user_form = UserEditForm(instance=request.user)

   return render(request,
                 'registration/edit.html',
                 {'user_form': user_form,})

@ajax_required
@require_POST
def ajax_newsletter(request):
    post_val = request.POST.get('newsmail')

    if post_val :
        newsletter = Newsletter(newsemail=post_val)
        saving = newsletter.save()
        if saving:
            return JsonResponse({'status':'ok'})
        else:
            return JsonResponse({'status':'false'})
    else:
        return JsonResponse({'status': 'false'})

bet/templates/bet/ad_top.html
{% if blockpano %}
    {% for block in blockpano %}
        {{ block.body|safe }}
{% endfor %}
{% endif %}

bet/templates/bet/article.html
{% extends "layout.html" %}
{% load bet_tags %}
{% load thumbnail %}
{% load staticfiles %}
   {% block title %}{% for tag in post.tags.all %}{{ tag.name }} |{% endfor %}{{ post.title }}{% endblock %}
   {% block content %}
     <!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-579240e8e6c6261b"></script>


                    <article id="post-4795" class="clearfix post-4795 post type-post status-publish format-standard has-post-thumbnail hentry category-review category-social tag-adipiscing tag-amet tag-android tag-consectetur tag-css3 tag-dolor tag-google tag-great tag-html5 tag-ipsum tag-jquery tag-lorem tag-responsive tag-seo tag-shahrzad tag-sit tag-theme" role="article" itemscope="" itemtype="http://schema.org/BlogPosting">
                        <header class="article-header">

                <h1 class="entry-title single-title" itemprop="headline">{{ post.title }}</h1>
                <div class="row"><div class="col-sm-6"><div class="c5-author-meta-wrap"><div class="c5-author-img"><img alt="&lt;span class=&quot;fa fa-user&quot;&gt;&lt;/span&gt;" src="{% static 'images/article.jpg' %}" srcset="{% static 'images/article.jpg' %} 2x" class="avatar avatar-200 photo" height="200" width="200"></div>
                    <div class="c5-author-data"><a class="url fn" href="http://betvision.gr">Betvision</a>
                        <div class="">
                        <a href="https://twitter.com/betvisiongr" class="twitter-follow-button" data-show-count="false">Follow @betvisiongr</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                        <div id="fb-root"></div>
              <script>(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/el_GR/sdk.js#xfbml=1&version=v2.7&appId=114634571961506";
                fjs.parentNode.insertBefore(js, fjs);
              }(document, 'script', 'facebook-jssdk'));</script>
                    </div><div class="float_left_fb">
                    <div class="fb-like" data-href="https://web.facebook.com/betvision.gr/?fref=ts" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="false"></div>
                    </div></div></div></div><div class="col-sm-6"><div class="c5-author-meta-wrap"><div class="c5-author-img">
<img alt="" class="fa fa-user" src="{% static 'images/article1.jpg' %}" srcset="{% static 'images/article1.jpg' %} 2x" class="avatar avatar-200 photo" height="200" width="200">
</div><div class="c5-author-data"><time class="value updated" datetime="{{ post.created }}"><span class="fa fa-calendar-o"></span>{{ post.created }}</time><div class="clearfix"></div><div class="clearfix"></div>
                    <br><b>Share:</b><br> <div class="addthis_sharing_toolbox"></div><div class="clearfix"></div></div></div></div>
                    </div>
                          {% comment %} {% if 'kazino' not in show_image and 'poker' not in show_image  %}
                            <div class="c5-thumb-hover  clearfix" style="min-height:250px"><div class="c5-post-chfbq c5-post-thumb"><style>.c5-post-chfbq{background-image:url('{% thumbnail post.image 650x250  %}');min-height:250px;} @media
			only screen and (-webkit-min-device-pixel-ratio: 2),
			only screen and (   min--moz-device-pixel-ratio: 2),
			only screen and (     -o-min-device-pixel-ratio: 2/1),
			only screen and (        min-device-pixel-ratio: 2),
			only screen and (                min-resolution: 192dpi),
			only screen and (                min-resolution: 2dppx) { .c5-post-chfbq{background-image:url('{% thumbnail post.image 650x250 crop %}');}}</style></div></div>
                            {% endif %}{% endcomment %}
                            <div style="min-height:30px"></div>

                                      </header>


            <section class="entry-content c5-article-content clearfix" itemprop="articleBody">
                {{ post.body|safe }}
                </section>

                <footer class="article-footer">
                                      <div class="c5-tags-wrap clearfix"> <h3 class=" c5ab-title-VyjZH   normal title  clearfix"><span class="text-wrap"><span class="icon fa fa-tag"></span><span class="text ">Κατηγορίες</span></span></h3>
                    <div class="tags-meta tags clearfix">
                        {% for tag in post.tags.all %}
                        <a href="{% url "bet:post_list_by_tag" tag.slug %}" rel="tag">{{ tag.name }}</a>
                        {% endfor %}
                        <div class="clearfix"></div></div>
                    </div>

                    <div class="c5-related-wrap clearfix">
                        <h3 class=" c5ab-title-zQSlN   normal title  clearfix"><span class="text-wrap"><span class="icon fa fa-tags"></span><span class="text ">Περισσότερα Άρθρα</span></span></h3>

                        <div class="row">
                             {% for post in similar_posts %}
                            <div class="col-sm-4"><article class=" c5ab_posts_thumb_boxes_single clearfix"><div class="c5-boxes-thumb-hover  clearfix"><div class="c5-post-{{ post.id }} }} c5-post-thumb"><style>.c5-post-{{ post.id }}{background-image:url('{% thumbnail post.image 197x197  %}');min-height:197px;} @media
			only screen and (-webkit-min-device-pixel-ratio: 2),
			only screen and (   min--moz-device-pixel-ratio: 2),
			only screen and (     -o-min-device-pixel-ratio: 2/1),
			only screen and (        min-device-pixel-ratio: 2),
			only screen and (                min-resolution: 192dpi),
			only screen and (                min-resolution: 2dppx) { .c5-post-{{ post.id }} {background-image:url('{% thumbnail post.image 197x197  %}');}}</style></div></div><div class="box-content "><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></div></article></div>
                            {% empty %}
                            No post yet
                            {% endfor %}
                           </div>

                    </div>

                </footer>












            </article>






   {% endblock %}

bet/templates/bet/asianhandicap.html
{% extends 'layout.html' %}
{% block title %}Asian Handicap{% endblock %}
{% block content %}
<div id="c5_bread_crumb" class=" c5-single-element c5-breaking-1170-S-C-B">
                <div class="border">
                    <div id="title_crumb">
                        <h1 class="heading1">{{ tag.name }}</h1>
                        <div class="clearfix"></div>
                        <div id="crumbs"><a href="{% url "bet:index" %}"> <span class="fa fa-home"> </span> </a>  <span class="fa fa-caret-right"> </span>  <span class="current">Asian Hnadicap</span></div>                        <div class="arrow_down"></div>

                        <div class="clearfix"></div>
                    </div>
                </div>
              </div>
<div><iframe id="asian" name="asian" scrolling="no" src="http://www.infobeto.com/tools/asiancalcp.php?bgcolor=d63737&amp;fcolor=0a0606" frameborder="0" height="600px" width="500px"></iframe><p><a href="http://www.infobeto.com" target="_blank" title="Στοίχημα">powered by infobeto.com</a></p></div>
{% endblock %}

bet/templates/bet/breaking.html
{% for post in breaking_news %}
    <li>
        <a class="c5-cat" href="{{ post.get_absolute_url }}"  style="color:#e53935;" ><span class="fa fa-star"></span>{{ post.title }}</a></li>
{% endfor %}

bet/templates/bet/contact.html
{% extends "layout.html" %}
   {% block title %}Επικοινωνία{% endblock %}
   {% block content %}
       {% if form.errors %}
           <div class="alert alert-danger">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Προσοχή!</strong> Έχετε κάποιο λάθος στην υποβολή της φόρμας σας.
        </div>
       {% endif %}
     {% if sent %}
       <h1>Το email σας στάλθηκε επιτυχώς.</h1>
         <p>Ευχαριστούμε που επικοινωνήσατε μαζί μας.</p>
     {% else %}
       <h2>Επικοινωνήστε μαζί μας </h2>

         <form id="c5-contact-form" class="clearfix" method="post" action=""><div class="row"><div class="col-md-6">
             {% csrf_token %}
    		<div class="input-wrap"><input type="text" name="name" class="element-block" id="id_name" placeholder="Όνομα" size="20"><span class="fa fa-user"></span></div>
    		</div><div class="col-md-6">
    		<div class="input-wrap"><input type="text" name="email" class="element-block" id="id_email" placeholder="Email" size="20"><span class="fa fa-envelope"></span></div>
      </div></div><textarea id="id_comments" placeholder="Το μήνυμά σας ..." name="comments" class="element-block" tabindex="4" aria-required="true"></textarea>

             <input name="submit" type="submit" id="c5-submit-contact" value="Αποστολή">
             <div class="clearfix"></div>
         </form>
     {% endif %}

   {% endblock %}

bet/templates/bet/livestreaming.html
{% extends 'layout.html' %}
{% block title %}LiveStreaming{% endblock %}
{% block content %}
<div id="c5_bread_crumb" class=" c5-single-element c5-breaking-1170-S-C-B">
                <div class="border">
                    <div id="title_crumb">
                        <h1 class="heading1">{{ tag.name }}</h1>
                        <div class="clearfix"></div>
                        <div id="crumbs"><a href="{% url "bet:index" %}"> <span class="fa fa-home"> </span> </a>  <span class="fa fa-caret-right"> </span>  <span class="current">Live Streaming</span></div>                        <div class="arrow_down"></div>

                        <div class="clearfix"></div>
                    </div>
                </div>
              </div>
<div><iframe scrolling="no" src="http://www.livefootball.gr/widget/stream-widget.php?height=800&amp;color=EBE5EB&amp;textcolor=000000&amp;language=el" style="overflow:hidden;background:#fff;" frameborder="0" height="800" width="600"></iframe></div>
{% endblock %}

bet/templates/bet/newsletter.html
{% load bet_tags %}
{% comment %}<form action="{% url "bet:newsletter" %}/" method="post">
    <div class="input-wrap">
        {% csrf_token %}
       {{ newsletter.as_p }}
        </div>
       <p><input id="c5-submit-newsletter" type="submit" value="Subscribe"></p>
   </form>{% endcomment %}

<form action="/newsletter/" method="post" id="c5-newsletter-form">
                      {% csrf_token %}
    <div class="input-wrap">
{{ newsletter.as_p }}
        </div>
        <p><input id="c5-submit-newsletter" type="submit" value="Subscribe"></p>
   </form>